// import 'bootstrap/dist/css/bootstrap.min.css'
// import 'jquery/dist/jquery.min.js'
// import 'popper.js/dist/popper.min'
// import 'bootstrap/dist/js/bootstrap.min.js'
// import 'bootstrap/js/dist/util'
// import 'bootstrap/js/dist/carousel'
// import 'bootstrap/js/dist/dropdown'

import './src/styles/index.sass'
import 'bootstrap/dist/js/bootstrap.min.js'
